version: '3.2'
services: 
  # backend:
  #   build: ./app

  nginx:
    build: ./nginx
    ports:
      - '80:80'
      # - '443:443'
    volumes:
      - certs:/etc/letsencrypt
      - certs_data:/data/letsencrypt

  letsencrypt:
    image: deliverous/certbot
    volumes:
      - certs:/etc/letsencrypt
      - certs_data:/data/letsencrypt
    command: "certonly --webroot --webroot-path=/data/letsencrypt --renew-by-default -d birthdaybuddy.io --email mattcarpowich@gmail.com --agree-tos --no-eff-email --non-interactive"

  # postgres:
  #   image: postgres:9.3
  #   environment:
  #     - POSTGRES_USER=user
  #     - POSTGRES_PASSWORD=password
  #     - POSTGRES_DB=birthdaybuddydb
  #   ports:
  #     - "5432:5432"

  volumes:
    backend:
    certs:
    certs_data: